__version__ = "1.0.1"
__author__ = "Job Snijders"
__author_email__ = "job@instituut.net"
__copyright__ = "Copyright 2017-2018, Job Snijders"
__license__ = "BSD 2-Clause"
__status__ = "Stable"
__url__ = "https://github.com/job/rtrsub"
